CREATE TABLE IF NOT EXISTS stages (
    id SERIAL PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    background_img VARCHAR(255) NOT NULL,
    difficulty INT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);